# Site settings
title: seoatiiit
description: seoatiiit is a search engine optimization(SEO) contest held at IIIT Bhubaneswar.
keywords: seoatiiit, advaita, seo ,iiit
author: Shibasis Patel
baseurl: "" 
url: "" 
gems:
  - jekyll-sitemap
